language: python
python:
  - "3.6"
cache: pip
before_install:
  # grab repo
  - openssl aes-256-cbc -K $encrypted_003878c977d9_key -iv $encrypted_003878c977d9_iv -in pk.enc -out pk -d
  - chmod 600 pk
  - eval $(ssh-agent -s)
  - ssh-add pk
  - git clone git@github.com:nzoghb/dagora-chain.git
  # use node
  - nvm install node
  - nvm use node
install:
  - pip install -r requirements.txt
  # install IPFS
  - wget "https://dist.ipfs.io/go-ipfs/v0.4.9/go-ipfs_v0.4.9_linux-amd64.tar.gz" -O /tmp/ipfs.tar.gz
  - pushd . && cd $HOME/bin && tar -xzvf /tmp/ipfs.tar.gz && popd
  - export PATH="$HOME/bin/go-ipfs:$PATH"
  # install lotion
  - npm i lotion@0.1.18
before_script:
  - node ./dagora-chain/app_trivial.js &
  - ipfs init
  - ipfs daemon &
  - sleep 5
script:
  - curl http://localhost:3000/state
  - curl http://localhost:5001/api/v0/id
  - pytest tests