language: python
python:
  - "3.6"
cache:
  - pip
  - npm
before_install:
  # grab repo
  - openssl aes-256-cbc -K $encrypted_003878c977d9_key -iv $encrypted_003878c977d9_iv -in pk.enc -out pk -d
  - chmod 600 pk
  - eval $(ssh-agent -s)
  - ssh-add pk
  - git clone git@github.com:nzoghb/dagora-chain.git
  # use node
  - nvm install 8
  - nvm use node
  - npm -v
  - node -v
install:
  - pip install -r requirements.txt
  # install IPFS
  - wget "https://dist.ipfs.io/go-ipfs/v0.4.9/go-ipfs_v0.4.9_linux-amd64.tar.gz" -O /tmp/ipfs.tar.gz
  - pushd . && cd $HOME/bin && tar -xzvf /tmp/ipfs.tar.gz && popd
  - export PATH="$HOME/bin/go-ipfs:$PATH"
  # install lotion and other node dependencies
  - cd ./dagora-chain
  - npm ci
before_script:
  - node ./app.js &
  - cd ..
  - ipfs init
  - ipfs daemon &
  - sleep 5
script:
  - curl http://localhost:3000/state
  - curl http://localhost:5001/api/v0/id
  - pytest tests
